% RUN_TRAPEZOIDAL  Example: 2D thin-film TDGL simulation with trapezoidal solver.
%
%   Simulates a 60×60×3 superconductor with κ=5 under applied Bz=0.6,
%   using the implicit trapezoidal integrator with adaptive time stepping.
%
%   This script demonstrates the recommended workflow:
%     1. Set up parameters
%     2. Build grid indices
%     3. Create initial state
%     4. Run time integration
%     5. Visualize results
%
%   See also SETUP_PARAMETERS, TRAPEZOIDAL_SOLVER, PLOT_FIELDS_2D

clear; close all; clc;

% Add all subdirectories to path
run(fullfile(fileparts(mfilename('fullpath')), '..', 'setup_paths.m'));

%% ==================== 1. Parameters ====================
params = setup_parameters( ...
    'Nx',           60, ...
    'Ny',           60, ...
    'Nz',           3, ...
    'hx',           1, ...
    'hy',           1, ...
    'hz',           1, ...
    'kappa',        5, ...
    'applied_Bx',   0, ...
    'applied_By',   0, ...
    'applied_Bz',   0.6, ...
    'dt',           0.1, ...
    't_start',      0, ...
    't_stop',       20, ...
    'periodic_x',   false, ...
    'periodic_y',   false, ...
    'periodic_z',   false, ...
    'slice_z',      1, ...
    'frames',       100, ...
    'visualize_save', true);

%% ==================== 2. Grid Indices ====================
params = construct_grid_indices(params);

%% ==================== 3. Precompute Phi Laplacians ====================
% These are constant (independent of state), so build once.
params.L_phi_x_precomputed = construct_lphi_x(params);
params.L_phi_y_precomputed = construct_lphi_y(params);
params.L_phi_z_precomputed = construct_lphi_z(params);

%% ==================== 4. Initial State ====================
initial_state = create_initial_state(params, 'perturbation', 0.01, 'seed', 42);

%% ==================== 5. Run Simulation ====================
fprintf('Starting trapezoidal simulation...\n');
fprintf('  Grid: %d × %d × %d, κ = %.1f, Bz = %.2f\n', ...
    params.Nx, params.Ny, params.Nz, params.kappa, params.applied_Bz);
fprintf('  dt = %.3f, t_stop = %.1f\n', params.dt, params.t_stop);

[state_history, params] = trapezoidal_solver( ...
    @evaluate_rhs, initial_state, params, @evaluate_applied_field, ...
    params.t_start, params.t_stop, params.dt, []);

fprintf('Simulation complete. %d time steps taken.\n', size(state_history, 2) - 1);

%% ==================== 6. Visualize ====================
plot_fields_2d(state_history, params, 'save_gif', params.visualize_save);

fprintf('Done.\n');
