% RUN_FORWARD_EULER  Example: 3D TDGL simulation with explicit Forward Euler.
%
%   Simulates a 30×30×30 superconductor with κ=5 under applied Bz=0.6,
%   using the explicit Forward Euler integrator. Requires small dt for
%   stability (CFL condition).
%
%   See also SETUP_PARAMETERS, FORWARD_EULER, PLOT_FIELDS_3D

clear; close all; clc;

% Add all subdirectories to path
run(fullfile(fileparts(mfilename('fullpath')), '..', 'setup_paths.m'));

%% ==================== 1. Parameters ====================
params = setup_parameters( ...
    'Nx',           30, ...
    'Ny',           30, ...
    'Nz',           30, ...
    'hx',           1, ...
    'hy',           1, ...
    'hz',           1, ...
    'kappa',        5, ...
    'applied_Bx',   0, ...
    'applied_By',   0, ...
    'applied_Bz',   0.6, ...
    'dt',           1e-3, ...
    't_start',      0, ...
    't_stop',       1, ...
    'periodic_x',   false, ...
    'periodic_y',   false, ...
    'periodic_z',   false, ...
    'slice_z',      0, ...
    'frames',       50, ...
    'visualize_save', false);

%% ==================== 2. Grid Indices ====================
params = construct_grid_indices(params);

%% ==================== 3. Initial State ====================
initial_state = create_initial_state(params, 'perturbation', 0.01, 'seed', 42);

%% ==================== 4. Run Simulation ====================
fprintf('Starting Forward Euler simulation...\n');
fprintf('  Grid: %d × %d × %d, κ = %.1f, Bz = %.2f\n', ...
    params.Nx, params.Ny, params.Nz, params.kappa, params.applied_Bz);
fprintf('  dt = %.1e, t_stop = %.1f\n', params.dt, params.t_stop);

state_history = forward_euler( ...
    @evaluate_rhs, initial_state, params, @evaluate_applied_field, ...
    params.t_start, params.t_stop, params.dt, []);

fprintf('Simulation complete. %d time steps taken.\n', size(state_history, 2) - 1);

%% ==================== 5. Visualize ====================
plot_fields_3d(size(state_history, 2), state_history, params);

fprintf('Done.\n');
